# A minimal left prompt
# format = """$character"""

# move the rest of the prompt to the right
# right_format = """$all"""

command_timeout = 100

[nodejs]
symbol = "â–"
format = "[$symbol($version )]($style)"
# disabled = false

[aws]
disabled = true

[gcloud]
disabled = true

[git_branch]
# symbol = "ğŸŒ± "
# symbol = "â‡ "
symbol = "â‘‚ "

[git_status]
disabled = true
